### ISSUE TITLE
Generated inner `enum` classes cannot be annotated with `@Deprecated`

### ISSUE THREAD

**Issue by Chrimle** [Chrimle/openapi-to-java-records-mustache-templates#186]
**Describe the bug**
Inner enum classes are not annotated as deprecated. This is due to `openapi-generator-maven-plugin`.
This problem was discovered as part of #185 

**To Reproduce**
Given an OpenAPI Spec:
```yaml
    RecordWithInnerEnums:
      type: object
      description: Example of a Record with inner enum classes
      properties:
        exampleInner:
          type: string
          description: Example of an inner enum class
          enum:
            - ENUM1
            - ENUM2
            - ENUM3
        exampleInnerTwo:
          type: string
          deprecated: true
          description: Example of another inner enum class
          enum:
            - ENUM1
            - ENUM2
            - ENUM3
```
The `exampleInnerTwo` enum class will not be annotated deprecated.

**Expected behavior**
Inner enum classes should be annotated correctly...
