### ISSUE TITLE
Inner class is not generated & outer class is named incorrectly

### ISSUE THREAD

**Issue by Chrimle** [Chrimle/openapi-to-java-records-mustache-templates#6]
With the following minimal reproducible example:
```yaml
components:
  schemas:
    ClassA:
      type: object
      properties:
        ClassB:
          type: object
          properties:
            text:
              type: string
```
the generated record class will be the following:
```java
package com.chrimle.example;

import java.util.List;

/**
 * 
 * @param text 
 */
public record ClassAClassB(
    String text) {

}
```
There are several issues here...
